name: "high-power-fpv"
author: "OpenIPC Dev"
description: "Description of high-power-fpv."
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "Experimental"
tags: [ "high-power", "fpv" ]
files:
  wfb.yaml:
    wireless.channel: "161"
    wireless.txpower: "20"
    broadcast.stbc: "0"
    broadcast.ldpc: "0"
    broadcast.mcs_index: "1"
    broadcast.tun_index: "1"
    broadcast.fec_k: "8"
    broadcast.fec_n: "12"  
    telemetry.serial: ttyS2
    telemetry.router: msposd
  majestic.yaml:
    fpv.enabled: "false"
    system.logLevel: "debug"
    video0.codec: "h264"
    video0.fps: "120"
