name: "runcam2-preset"
author: "carabidule"
description: "msp menu, tx power mw"
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "stable"
tags: ["runcam", "msp"]
files:
  wfb.yaml:
wireless:
  txpower: 30
  channel: 161
  width: 20
broadcast:
  mcs_index: 2
  tun_index: 1
  fec_k: 8
  fec_n: 12
  stbc: 1
  ldpc: 1
  link_id: 7669206
telemetry:
  router: msposd
  serial: ttyS2
  osd_fps: 20


  majestic.yaml:
    fpv.enabled: "true"
    fpv.noiseLevel: "0"
    system.logLevel: "debug"
    video0.codec: "h265"
    video0.fps: "120"
    video0.bitrate: "4096"
    video0.size: "1280x720"
  
  external_files:
    vtxmenu.ini
     
  
    
